### ISSUE TITLE
please clarify move to GPL

### ISSUE THREAD

**Issue by amitport** [pakastin/deck-of-cards#13]
You've mentioned that you moved to GPL in order to respect Chris Aguilar's http://sourceforge.net/projects/vector-cards/. 

IMHO, you need not do that:
First, only your svg changes are derivative, so you can just release those *separately* under LGPL (can include it in a different repo to be more clear about that)
Second, Chris Aguilar's lib is LGPL so even if you thought it applies for all you code for some reason, you only need to license as LGPL.

**Comment by pakastin** [comment]
I will change to LGPL and after I've moved graphics to another repo, I can change back to MIT. Sorry I don't know that much about licenses, I just read from somewhere that if a dependency is GPL, you should also use GPL. Thank you so much for bringing this out! ;)

**Comment by amitport** [comment]
thanks! :relieved:

**Comment by Shuunen** [comment]
I learn something today, thanks @amitport 

I was used to choose GPL but I realize it's a bit strong :)

https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License

**Comment by pakastin** [comment]
Yeah I will change it back to MIT when theming is ready..

**Comment by pakastin** [comment]
I don't understand any of that, but will change back to MIT as soon as theming is ready and the default theme moved away. If you use Deck of Cards (only dist/deck.min.js) without Chris's vector graphics, it's MIT - you can refer to here.

But I hope you still show me what you've done - it's interesting to see what people come up with :) And a little credit is always due ;)

**Comment by pakastin** [comment]
I updated readme and license to clarify it's MIT without Chris Aguilar's vector playing cards graphic set.
