### ISSUE TITLE
Alternative card faces

### ISSUE THREAD

**Issue by mwaclawek** [pakastin/deck-of-cards#25]
Why do you use the card faces from [1] when there is also [2]?

[1] is under the LGPL 3.0 and offers exceptions "on a negotiated fee basis".

[2] is in the public domain.

In fact, both are so similar that ...

 * one must be the copy of the other one
 * or
 * they must share a common original work that they're based on (which might be [here](https://en.wikipedia.org/wiki/United_States_Playing_Card_Company))

Anyway, it seems [2] was there first.

[1] https://code.google.com/p/vectorized-playing-cards/
[2] https://code.google.com/p/vector-playing-cards/

**Comment by pakastin** [comment]
Thanks for letting me know - I will check the other one. Remember I did a major parsing/modification for [1], which would take some time to go through again. But if [2] is worth it, I'll consider it.

I have already said here that if you use only my js code without the vector graphics, it's MIT. My intentions are only to inspire people to learn vanilla js.

But yeah, I will check that out and keep this open while at it - thanks!

I will also ask Chris Aguilar about this.

I also accept pull requests, if anyone's interested.. ;)

**Comment by pakastin** [comment]
I was on iPhone yesterday and couldn't investigate [2]. I did it now and realized those just aren't as good looking as [1]. I also contacted Chris Aguilar and he said that the both projects were created in 2011 without knowing from each other. Chris has since optimized it's own version a lot and I agree that they look much better.

Anyhow, you can use [2] if you want and it's MIT then. I will update readme and license -files to reflect that.

**Comment by pakastin** [comment]
Readme and license files updated. Closing this.

**Comment by mwaclawek** [comment]
Thank you!

The dates are correct, as [1] was published in April 2011 and [2] has been around since March 2011.

I don't agree that the cards from [1] "look and work so much better" because both sets are available as SVG and share *exactly* the same images.

The only differences are the card frame's padding around the images, the style of the card rank characters in the frame and the outlines. Obviously, these are all subtle differences.

I just thought that, because [users have been concerned with the license change](https://github.com/pakastin/deck-of-cards/issues/13), keeping this great library under MIT license only with the help of *public domain* card faces would be a good idea :)

But in the end, since it's your project, it's up to you which card faces you prefer, of course.

**Comment by pakastin** [comment]
I don't like i.e. the layout of 9's, size/quality of suit icons and especially jokers look really ugly in [2] (you can activate jokers in HTML Deck of Cards by clicking all kings in a row).

I have also chatted with Chris Aguilar and he said he's made lots of optimizations, which ensures good performance, small file sizes and superior quality in every screen size.

If someone makes good looking public domain card graphics, I'm happy to use them. [2] is not good enough in my opinion. If someone wants to make a branch for [2] and makes a pull request, I can merge it, but for the master branch I'll keep using Chris's graphics if nothing better comes out..
