### ISSUE TITLE
Make it easier to change card sizes

### ISSUE THREAD

**Issue by mizzao** [pakastin/deck-of-cards#27]
Right now the card sizes (including font) can be only be changed by setting `html { font-size: 200% }`, etc. This is because of the `rem` units used to determine the card size, which are [relative to the document root](https://css-tricks.com/theres-more-to-the-css-rem-unit-than-font-sizing/).

It seems that this could be fixed by simply using `em` units; then one could insert cards to a `div.deck` or something like that and just set `.deck { font-size: whatever }` using CSS. Is there anything else that might need to be changed for this?

Originally mentioned at https://github.com/pakastin/deck-of-cards/issues/8#issuecomment-160808300.

**Comment by pakastin** [comment]
Thanks, I'll investigate this!

**Comment by pakastin** [comment]
This is coming in the next version!
