### ISSUE TITLE
Make it easier to create a deck of other than 55 or 52 cards

### ISSUE THREAD

**Issue by mizzao** [pakastin/deck-of-cards#28]
Currently, because of all the functions in the closure of `deck.js`, it is hard to create a deck of anything other than the default size. It is possible to render individual cards using `Deck.Card`, but then there is no logical deck containing them that can be shuffled, sorted, fanned, etc. since the nice animation functions using `queue` and `observable` aren't accessible.

Since some games don't use all cards, would it be possible to specify a `Deck` constructor that takes an array of values from `[0, ..., 54]` and then use this to construct a deck with a subset of the cards?

**Comment by pakastin** [comment]
Yes, that's something I've thought about also. Right now I'm busy creating new version of my minimal vanillajs "framework", frzr.js.org - I might create a new version of deck of cards with FRZR once I get that ready. I get back to this issue..

**Comment by pakastin** [comment]
If you have some quick fix in mind, just drop a pull request and I'll check that out ;)

**Comment by pakastin** [comment]
Btw, with ```var deck = new Deck(true)``` you get jokers in! ;)

**Comment by Jorl17** [comment]
I have made some progress towards this. In my branch (http://github.com/jorl17/deck-of-cards) I have implemented a way for a Deck to hold multiple decks (e.g. it can hold two of each kind, or three, or four). Making a pull request (adjust code as you wish)

I have added the ability to represent cards by their english names (e.g. "Jack of Spades"). This helps with more generic and "exotic" decks in the future.

Thanks for your great work on this library!

**Comment by pakastin** [comment]
Wow, you've been busy! I'll get back to this tomorrow.. Thanks!

**Comment by JanisE** [comment]
Also, when I want to represent a player's hand, initially empty, I would like to create a `Deck` without any cards in it, and move/mount them in manually afterwards.

**Comment by pakastin** [comment]
I've started a rewrite of this project, that's the reason updates are a bit "frozen" at the moment..

**Comment by pakastin** [comment]
There's so many things could be done better.. When I started the project, it was just a demo – it was never designed to be an API.

**Comment by JanisE** [comment]
Well, it's the best API that I could find. :)

**Comment by pakastin** [comment]
Can imagine :D

**Comment by pakastin** [comment]
Here's a small sneak peak of what's coming: https://github.com/pakastin/cards 😎

Notice though that that repo will be merged here and removed..

**Comment by clemishow** [comment]
@pakastin Hey, how can I can the number of cards in my js ? Thank you

**Comment by pakastin** [comment]
Coming in the next version!
