### ISSUE TITLE
Rotation information is lost after second rotation

### ISSUE THREAD

**Issue by Jorl17** [pakastin/deck-of-cards#30]
If you rotate a card and then rotate it a second time, the original rotation information is lost (it goes back to 0, instead of rotating from the original position). I might have fixed this and might link to this issue from a commit soon

**Comment by Jorl17** [comment]
If you merge https://github.com/pakastin/deck-of-cards/pull/29 , the fix is included :)

**Comment by pakastin** [comment]
I'm currently rewriting the project, so that's why PRs are unfortunately freezed.. I'll let you know as soon as I have things to show! 😎

Thank you so much anyway!
