### ISSUE TITLE
Lack of delay parameter in animateTo makes animation fail

### ISSUE THREAD

**Issue by Jorl17** [pakastin/deck-of-cards#31]
It's really just a tiny bug, but it can be annoying and dodgy. If you don't pass the delay parameter to the `animateTo` function, it oopses and doesn't animate. I have fixed this with a one-liner in https://github.com/Jorl17/deck-of-cards/commit/4079b6e5da7bea6aa82c8a1543fc04b5d683e114.

**Comment by pakastin** [comment]
Thank you so much, João! Will get back to this also tomorrow..

**Comment by pakastin** [comment]
This will be fixed in the next version!
