### ISSUE TITLE
Blank cards on Iphone's 5s Browser

### ISSUE THREAD

**Issue by mtheus** [pakastin/deck-of-cards#33]
![ah-1rq0iynj4sgbmhrg5quugiphzicser2rcylm-3s1x](https://cloud.githubusercontent.com/assets/2132299/13415094/bafc7dbe-df36-11e5-88ea-c401ea68972a.jpg)

**Comment by pakastin** [comment]
Hi! Could you give some more details of the issue? I see the browser is still loading, so could it just be that? Or maybe some temporal network issue?

Graphics are separate files which might fail to load, that's just how the internet works..

**Comment by pakastin** [comment]
Closed for now, please provide more details if the problem continues..

**Comment by mtheus** [comment]
I tryed to reproduce, but nothing, could be a network issue, I agree! It is on your roadmap, use a sprite instead of separeted images and maybe control the loading dependences? Thank you! =)
