### ISSUE TITLE
Corner numbers of face-down cards visible initially

### ISSUE THREAD

**Issue by JanisE** [pakastin/deck-of-cards#36]
If I comment out `deck.intro()` in `example.js:183` leaving only sorting after the creation and mounting of the deck, the corner numbers of cards are still visible even if they are supposed to be face down.

The numbers disappear upon flipping them over and over again (clicking by mouse two times), but they are visible in the intial view.

In both Chrome 57 and Firefox 52 (Linux versions).

**Comment by pakastin** [comment]
Thanks, I check it out!

**Comment by pakastin** [comment]
Fixed now! 😉

**Comment by JanisE** [comment]
Wow, that was super-fast! Thanks!
