### ISSUE TITLE
Typescript import

### ISSUE THREAD

**Issue by clemishow** [pakastin/deck-of-cards#37]
Hello,

I'm trying to use your plugin into an Ionic app (version 2).

I used NPM and save into dependencies.

Then I import into my file home.ts

```
import { Component, ElementRef, OnInit } from '@angular/core';
import { NavController } from 'ionic-angular';
import * as Deck from 'deck-of-cards';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html',
})
export class HomePage implements OnInit {
  public container :any;

  constructor(public navCtrl: NavController, public el: ElementRef) {
    console.log(Deck);
  }

  ngOnInit() {
    this.container = this.el.nativeElement.querySelector('#container');
    console.log(this.container);
  }

}
```

The console log return a empty object

**Comment by pakastin** [comment]
Hi!

I've never used TypeScript, but try `import Deck from 'deck-of-cards';`

**Comment by pakastin** [comment]
I also added `"module"` field to `package.json` (run `npm i deck-of-cards` to update v0.1.8).

_btw. I'm currently rewriting the project.._

**Comment by clemishow** [comment]
It worked ! Thank you
