### ISSUE TITLE
translate3d or translateZ(0)

### ISSUE THREAD

**Issue by bringking** [pakastin/deck-of-cards#4]
For better perf, you should switch to using translate3d or add translateZ(0) to your transform string. Really consider using the "3d" equivalents for each of the transforms, to force the GPU to do the heavy lifting. Not sure in this example it will be a huge win, but a good thing to keep in mind.

**Comment by pakastin** [comment]
I actually tried that, but it makes the cards more blurry – I don't like that.. :/
I could make the translate3d's temporary though to fix the blurryness. Let's see..

**Comment by send2moran** [comment]
you can use,  will-change: transform;
