### ISSUE TITLE
Change Card Size and Position

### ISSUE THREAD

**Issue by kenshinbat** [pakastin/deck-of-cards#41]
Hi,

Can you please point to me how I can change the card sizes and position?
I have tried editing the .card class width and height in example.css but the cards overlap on deal(more pronounced with Poker and By Suit display). 

Thanks

**Comment by pakastin** [comment]
Yeah, it's unfortunale hardcoded here:
https://github.com/pakastin/deck-of-cards/blob/7afec8d2585b683445f03aa9a8655283be4b87e5/lib/modules/poker.js#L36-L37

and:

https://github.com/pakastin/deck-of-cards/blob/7afec8d2585b683445f03aa9a8655283be4b87e5/lib/modules/bysuit.js#L36-L37

I'm currently rewriting the project, so this will change in the future.. I hope to get it forward during the weekend.

**Comment by kenshinbat** [comment]
Will be extremely glad if you can make it work, I have been stuck on fixing it for a month now. Can't wait till its the weekend.

Thanks

**Comment by pakastin** [comment]
Basically you could customize those modules:
```
var SIZE = 1;

deck.bysuit = deck.queued(function (next) {
  deck.cards.forEach(function (card, i) {
    var i = card.i;
    var delay = i * 10;

    card.animateTo({
      delay: delay,
      duration: 400,

      x: -Math.round((6.75 - rank) * 8 * SIZE),
      y: -Math.round((1.5 - suit) * 92 * SIZE),
      rot: 0,

      onComplete: function () {
        cb(i);
      }
    });
  });
});
```

**Comment by pakastin** [comment]
..and poker:

```js
deck.poker = deck.queued(function (next) {
  deck.cards.forEach(function (card, i, len) {
    var delay = i * 250;

    card.animateTo({
      delay: delay,
      duration: 250,

      x: Math.round((i - 2.05) * 70 * SIZE),
      y: Math.round(-110 * SIZE),
      rot: 0,

      onStart: function () {
        card.$el.style.zIndex = (len - 1) + i;
      },

      onComplete: function () {
        card.setSide('front');
        if (i === 4) {
          next();
        }
      }
    });
  }); 
});
```

**Comment by pakastin** [comment]
Should work, I tried it with `example.html`.. 😉

**Comment by pakastin** [comment]
..and like I said I try to get the next-gen version hopefully done during this weekend ;)

**Comment by kenshinbat** [comment]
It didn't work when I tried it, when I click the Poker and Bysuit buttons, the cards don't deal.
Am I replacing the whole codes in the modules or inserting them from a specific line?

**Comment by pakastin** [comment]
Call `deck.shuffle()` first couple of times 😉

**Comment by pakastin** [comment]
Check out: https://github.com/pakastin/deck-of-cards/blob/master/example/example.js

**Comment by pakastin** [comment]
So:
```deck
.shuffle()
.shuffle()
.poker();
```

**Comment by kenshinbat** [comment]
Hi,
I am not getting a hang of this it all. I have explained what I need in the images attached. Thanks
<img width="512" alt="screen shot 2017-10-13 at 10 37 41 am" src="https://user-images.githubusercontent.com/29722116/31540657-259408a0-b004-11e7-8591-804c2ae6db9b.png">
<img width="512" alt="screen shot 2017-10-13 at 10 41 05 am" src="https://user-images.githubusercontent.com/29722116/31540658-26cf3154-b004-11e7-9530-bf819f7b6f85.png">
<img width="512" alt="screen shot 2017-10-13 at 10 42 32 am" src="https://user-images.githubusercontent.com/29722116/31540666-288b6378-b004-11e7-9743-ec9903e1c0f3.png">

**Comment by pakastin** [comment]
Try set the `SIZE` so that if cards are too close to each other, raise the value and vice versa. If you need a separate Y-value, just add `SIZE_Y` etc.. :)

**Comment by kenshinbat** [comment]
What script file, example.js?

**Comment by kenshinbat** [comment]
Hi, 
any luck with the upgrade? I still can't re-arrange the cards. Can you do a replica in the poker script? Just increase the size of the Cards and space them. Thanks

**Comment by pakastin** [comment]
Sorry, I got busy with an urgent client work. I’ll work an example for you after couple of hours..

**Comment by pakastin** [comment]
Here's an example: https://jsfiddle.net/o5vkm5qz/

You can change the card size in the CSS and it will position accordingly.. (poker + by suit)

**Comment by kenshinbat** [comment]
Thanks a bunch bro. Been off the project for a while, works fine on jsfiddle. Will check with my project and get back to you.

**Comment by kenshinbat** [comment]
Hi friend,
Thanks for the help so far, I am back on the project now and still haven't figured out a way to make the cards display in different positions. Attached is the image showing the display intended. Any help please. Thanks
<img width="512" alt="screen shot 2017-10-13 at 10 42 32 am" src="https://user-images.githubusercontent.com/29722116/35309873-cc6a1c14-00ae-11e8-9938-3922f2d0c0b0.png">

**Comment by pakastin** [comment]
This will get so much easier in the next version!
