### ISSUE TITLE
make another card image

### ISSUE THREAD

**Issue by lee-ji-eun** [pakastin/deck-of-cards#42]
Can I create a card with a different number of image files?
ex ) tarot card, game decks etc.

**Comment by pakastin** [comment]
Currently no, but I'm currently rewriting the project..

**Comment by pakastin** [comment]
..it will be more API-like, so after the rewrite it will possible! ;)

**Comment by lee-ji-eun** [comment]
Thank you for your response. :D

**Comment by jessebmiller** [comment]
Any update on the progress? Is the rewrite still active? Need a hand?

**Comment by pakastin** [comment]
It's active! https://medium.com/@pakastin/javascript-playing-cards-part-1-ranks-and-values-a9c2368aedbd 😉

**Comment by pakastin** [comment]
Yeah, preparing for the next version and closing old issues! I'll get back to you when I have something to show!
