### ISSUE TITLE
TCG use?

### ISSUE THREAD

**Issue by Gr33ntimer15** [pakastin/deck-of-cards#49]
This would be amazing to use as a base for online TCG unfortunately I don't know How to code very well yet and would have a very difficult time trying to implement it.

All you would really need to add/change is make it easy to change the Number of card and look of the cards as well as make it possible To Create randomized decks. (with some kinda of 2 player function)

~Gr33n

P.S. i really like this wish i new how to cod i tried changing the .svg files to change the images and it didn't work

**Comment by pakastin** [comment]
I'm sure you'll like the next version I'm currently working on! 😎

**Comment by Marak** [comment]
@pakastin Are there any updates on this? Is it possible easily create new cards with custom graphics in order to enable TCG?

**Comment by pakastin** [comment]
Next version is open source soon: https://deck.of.cards

**Comment by Marak** [comment]
Ok.

I don't see any TCG functionality there.

Can you please answer my question?

**Comment by pakastin** [comment]
What does TCG mean?

**Comment by Danny-Engelman** [comment]
TCG = Trading Card Game

So basically he wants to swap out all images/design with something custom like PokeMon cards.

**Comment by pakastin** [comment]
Yes, the new version supports custom card design
