### ISSUE TITLE
University offer

### ISSUE THREAD

**Issue by thelifewelive** [pakastin/deck-of-cards#50]
Hello!
Five university student is looking for an open source project. Our task in the university is find an open source project on git and help to make it better. We are really interested in this project, but our teacher says we have to work on an active project.
Firstly we would do the issues of course but we have a lot of idea to make this project better. We are thinking about that some AI make this project better to play poker or any other game.

Write back if you are interested in this concept.

**Comment by pakastin** [comment]
Hi! Yeah, I'm currently rewriting the project, so maybe after I release the updated version 🤔

But if you have any good ideas, I'm happy to hear! 👍
