### ISSUE TITLE
Cards flip to top- and backside randomely

### ISSUE THREAD

**Issue by Illusion935** [pakastin/deck-of-cards#51]
Hey there, 

When you use shuffle or sort, and move the cards, they randomely flip to top and backside. Is that meant to happen?

Cheers, Tom

Ps. I wanna use this in a schoolproject. Is that alright?

**Comment by pakastin** [comment]
Hi Tom!

You're right, haven't noticed that – it's not by purpose for sure..
I'm currently rewriting the project, it will be all different this time 😎

But yeah, it's open source with really permissive license (do notice graphics' license is difference), so just go for it – have fun and if you have any questions I'm happy to help! 😉
