### ISSUE TITLE
new version 

### ISSUE THREAD

**Issue by Wlada** [pakastin/deck-of-cards#52]
Hi Juha,

Thanks for sharing your work,  looks really good. I would love to use your module in my project which is in the development right now, but I found couple of comments where you referring that new version is coming out soon.  Do you have any idea when that can happen? 

Thanks, Vlad

**Comment by pakastin** [comment]
Just to let you know: new version is just around the corner.. 😉

**Comment by pakastin** [comment]
Tada! https://deck.of.cards

The new cards library will be open sourced soon here! 😉

**Comment by romaiiinnn** [comment]
Hi @pakastin thank you for this pretty awesome library. Do you have any update for the release of the new source code ?

Thank you!
