### ISSUE TITLE
Cool.  Might want to make numbers bigger (and suit icon count based on card value)

### ISSUE THREAD

**Issue by jimwhitfield** [pakastin/deck-of-cards#8]
Hi, nice work.  
If I were to use this for a game, I know I would want the card number image bigger and would really prefer the suit icon to be shown the number of times that matches the card value (i.e. 7 of spades should show seven spades, not just one.  When I drew a poker hand, my first reaction was "What? Two Ace of spades in one hand?")
The value and suit upside down on the bottom is a nice realistic touch.  Totally not needed for a virtual deck that can auto-rotate correctly, but cool.

**Comment by pakastin** [comment]
Hi, thanks!

I agree. Original Flash version actually had those: http://pakastin.fi/cards_2006
They are coming, I promise.... ;)

**Comment by mizzao** [comment]
Because the cards currently use `rem` units, it's very hard to change their size without changing the font size of the whole page: `html: { font-size: 200%; }`.

Maybe they can just use normal `em` units so that the parent container can be used to control the card size?

**Comment by pakastin** [comment]
@mizzao: Could you please make a new issue, thanks! This one's fixed and yours is a whole different problem.
