### ISSUE TITLE
Biased Shuffling

### ISSUE THREAD

**Issue by agrif** [pakastin/deck-of-cards#9]
It looks like your shuffling algorithm is pretty biased. In particular, [this bit](https://github.com/pakastin/deck-of-cards/blob/master/lib/deck-shuffle.js#L23):

~~~~{.js}
    cards.sort(function () {
      return Math.random() * 100 - 50
    })
~~~~

This is a random comparator sort, and [this page shows a bias matrix](http://bost.ocks.org/mike/shuffle/compare.html) for this algorithm by default.

Shuffling lists is a pretty surprisingly subtle problem. I'd recommend the [Fisher-Yates algorithm](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle), which helpfully has a demo javascript implementation on the bias matrix page.

It's also worth noting that [most implementations of Math.random() do not have enough bits of state](http://landing2.trusteer.com/sites/default/files/Temporary_User_Tracking_in_Major_Browsers.pdf) to access all possible shuffled decks. You need about 226 bits for a 52 card deck, but Firefox (for example) has 48.

**Comment by pakastin** [comment]
I know, I use Fisher-Yates a lot. The point here is to have it realistic: the more you shuffle the deck, the more random it gets - just like in the real world.

You could make another module for card games, when you need better randomness. These modules will become external and you can choose which ones to load in the near future.

Thanks anyway, I will keep this open until it haves Fisher-Yate as an option.

**Comment by agrif** [comment]
Ah ok. I was mostly worried that somebody would make a card game out of this expecting the shuffle to be unbiased. I get the feeling *most* programmers would look at your shuffle code and not see any problems.

**Comment by pakastin** [comment]
I was thinking that I should add a parameter to the shuffle -function:

deck.shuffle(true) // realistic shuffle
deck.shuffle() // Fisher-Yates

**Comment by Marak** [comment]
Reference: 

https://www.npmjs.com/package/knuth-shuffle
https://github.com/coolaj86/knuth-shuffle

**Comment by pakastin** [comment]
When shuffling two times (like in the Deck of Cards example), I'm getting equal results as with Fisher-Yates:

```
function shuffle(array) {
  array.sort(function() {
    return Math.random() - .5;
  });
  array.sort(function() {
    return Math.random() - .5;
  });
}
```
http://bost.ocks.org/mike/shuffle/compare.html

So I could as well use Fisher-Yates since it's much faster.. :)

Thanks for sharing the link!

**Comment by agrif** [comment]
Oooh interesting. On Chrome, the old algorithm has a nice solid green streak down the diagonal, and in Safari it does something weird with the top row, but on both of them running the old shuffle twice looks pretty unbiased. I wonder why.

I love this problem, I find it really interesting for some reason.

**Comment by pakastin** [comment]
Yeah, the problem itself is very random but the results not so much :D
